# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('group', models.CharField(max_length=20, verbose_name='Группа')),
                ('protocol', models.CharField(max_length=10, verbose_name='Протокол')),
                ('type', models.CharField(default='Датчик', max_length=10, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
