# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'main'), ('subordinate', 'subordinate')], default='subordinate', max_length=10, verbose_name='Роль устройства')),
                ('data_type', models.CharField(choices=[('coils', 'Coils'), ('discrete_inputs', 'Discrete Inputs'), ('input_registers', 'Input Registers'), ('holding_registers', 'Holding Registers')], default='Coils', max_length=20, verbose_name='Тип данных')),
            ],
            options={
                'verbose_name': 'Устройство modbus',
                'verbose_name_plural': 'Устройства modbus',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=20, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='device',
            name='group',
            field=models.CharField(blank=True, max_length=20, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Modbus'),
        ),
    ]
