# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170728_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'Датчик'), ('switcher', 'Реле')], default='sensor', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='modbus',
            name='data_type',
            field=models.CharField(choices=[('coils', 'Coils'), ('discrete_inputs', 'Discrete Inputs'), ('input_registers', 'Input Registers'), ('holding_registers', 'Holding Registers')], default='coils', max_length=20, verbose_name='Тип данных'),
        ),
    ]
